<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/05/07 14:18:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=sepro',
  'username' => 'admin',
  'password' => 'admin',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
